"""added stripe subscription id to user model

Revision ID: 739c7bec25dd
Revises: 0aa2804959d2
Create Date: 2025-06-19 22:49:05.548329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '739c7bec25dd'
down_revision = '0aa2804959d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stripe_subscription_id', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('stripe_subscription_id')

    # ### end Alembic commands ###
